name: Deploy to Scaleway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t demo/app:latest ./app

      - name: SCP Docker image to instance
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app"
          target: "/root"

      - name: SSH into server and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop demo-app || true
            docker rm demo-app || true
            docker rmi demo/app:latest || true
            docker build -t demo/app:latest /root/app
            docker run -d -p 80:80 --name demo-app demo/app:latest
