name: Build & Deploy App to Scaleway

on:
  push:
    branches: [dev]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/${{ secrets.SCW_REGISTRY_NAME }}
          username: ${{ secrets.SCW_REGISTRY_USER }}
          password: ${{ secrets.SCW_REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: rg.fr-par.scw.cloud/${{ secrets.SCW_REGISTRY_NAME }}/demo-app:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Write private key to file
        run: |
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
          
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yaml
          inventory: |
            [all]
            ${{ secrets.INSTANCE_IP }} ansible_user=root ansible_ssh_private_key_file=./id_rsa
          options: |
            -e registry_user=${{ secrets.SCW_REGISTRY_USER }}
            -e registry_token=${{ secrets.SCW_REGISTRY_TOKEN }}
            -e registry_name=${{ secrets.SCW_REGISTRY_NAME }}

  autoscaling:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Run autoscaling setup script
        run: |
          bash ../../scripts/autoscaling_setup.sh \
            # ${{ secrets.INSTANCE_ID }} \
            ${{ secrets.INSTANCE_VOLUME_ID }} \
            # # ${{ secrets.PRIVATE_NETWORK_ID }} \
            # ${{ secrets.SCW_PROJECT_ID }} \
            # ${{ secrets.LOAD_BALANCER_ID }} \
            # ${{ secrets.BACKEND_ID }}
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
          SCW_DEFAULT_ZONE: ${{ secrets.SCW_DEFAULT_ZONE }}


























          